# Generated by Django 4.1 on 2022-08-30 07:15

from django.db import migrations, models
import djongo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_users_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='users',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=djongo.storage.GridFSStorage(base_url='D:\\Projects\\GuviTask\\photos/', collection='photos'), upload_to='photos'),
        ),
    ]
